# Generated by Django 5.2.5 on 2025-09-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindmap',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
