# Generated by Django 5.2.5 on 2025-09-20 19:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_mindmap_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindmap',
            name='data',
            field=models.JSONField(blank=True, default=core.models.default_mindmap_data, null=True),
        ),
    ]
